[bar.main]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session"
]
font_weight = 400
scale = 1.1499999999999999
thickness = 36
widget_spacing = 8

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true

[hot_corners.top_right]
action = "control_center"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1536.0
    cy = 1609.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[plugins]
enabled = [ "mrsmsn/kdeconnect-reply", "noctalia/bongocat", "noctalia/screen_recorder" ]

[shell]
app_icon_color = "primary"
app_icon_colorize = true
ui_scale = 1.1000000000000001

    [shell.animation]
    speed = 1.3999999999999999

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Storm"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/mosh/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/mosh/Pictures/Wallpapers/1370824.png"

    [wallpaper.last]
    path = "/home/mosh/Pictures/Wallpapers/1370824.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/mosh/Pictures/Wallpapers/1370824.png"

[widget.control-center]
enabled = true

[widget.media]
enabled = true

[widget.network]
enabled = true
show_label = false