set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'airblade/vim-gitgutter'
Plugin 'mattn/vim-sqlfmt'
Plugin 'mattn/vim-lsp-settings'
Plugin 'mattn/vim-lsp-icons'
Plugin 'mattn/vim-goimports'
Plugin 'deton/jasegment.vim'
Plugin 'skanehira/translate.vim'
Plugin 'fatih/vim-go'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'leafgarland/typescript-vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'prabirshrestha/vim-lsp'
Plugin 'prabirshrestha/asyncomplete.vim'
Plugin 'prabirshrestha/asyncomplete-lsp.vim'
Plugin 'hrsh7th/vim-vsnip'
Plugin 'hrsh7th/vim-vsnip-integ'
Plugin 'cocopon/iceberg.vim'
call vundle#end()

set encoding=utf-8
scriptencoding utf-8

set ruler
set number
set t_Co=256
set background=dark
colorscheme iceberg

 autocmd ColorScheme * highlight LineNr ctermfg=12
 highlight CursorLineNr ctermbg=4 ctermfg=0
 set cursorline
 highlight clear CursorLine
 augroup TransparentBG
 autocmd!
  autocmd Colorscheme * highlight Normal ctermbg=none
  autocmd Colorscheme * highlight NonText ctermbg=none
  autocmd Colorscheme * highlight LineNr ctermbg=none
  autocmd Colorscheme * highlight Folded ctermbg=none
  autocmd Colorscheme * highlight EndOfBuffer ctermbg=none 
 augroup END

syntax enable

set noautoindent

let g:airline_theme = 'bubblegum'

let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1

set shiftwidth=4
set softtabstop=4
set tabstop=4

set expandtab
set smarttab

set visualbell t_vb=

set wrap

set noincsearch
set hlsearch
set ignorecase
set smartcase
set wrapscan
set gdefault

set list
set listchars=tab:>-,eol:↲,extends:»,precedes:«,nbsp:%

set wildmode=list:longest,full

set showcmd

set clipboard=unnamed

set whichwrap=b,s,h,l,<,>,~,[,]

set backspace=indent,eol,start
set nrformats-=octal

set pumheight=10

set showmatch
set matchtime=1
source $VIMRUNTIME/macros/matchit.vim

set display=lastline

set hidden

set nobackup
set noundofile
set noswapfile

nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k
nnoremap x "_x
nnoremap s "_s

inoremap <silent> jj <ESC>
inoremap <silent> ddd <C-R>=strftime("%Y-%m-%d")<CR> 
inoremap <silent> ttt <C-R>=strftime("%H:%M:%S")<CR>

nnoremap Y y$

nnoremap <silent><Esc><Esc> :<C-u>set nohlsearch!<CR>

vnoremap p "_dP

autocmd BufWritePre <buffer> LspDocumentFormat

let g:EasyMotion_leader_key = '<Space><Space>'
map f <Plug>(easymotion-f)
map t <Plug>(easymotion-t)
map F <Plug>(easymotion-F)
map T <Plug>(easymotion-T)
